project_id = "snnajdsrvufjynzblkmd"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.booking-reminders]
verify_jwt = false

[functions.create-station-owner]
verify_jwt = false

[functions.notify-station-owner]
verify_jwt = false
