project_id = "yhklvtzonvgzkodysawu"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.booking-reminders]
verify_jwt = false

[functions.create-station-owner]
verify_jwt = false

[functions.notify-station-owner]
verify_jwt = false

[functions.delete-station-owner]
verify_jwt = false

[functions.owner-self-register]
verify_jwt = false

[functions.owner-login-lookup]
verify_jwt = false

[functions.check-subscriptions]
verify_jwt = false

[functions.spin-booking-discount]
verify_jwt = false

[functions.cancel-map-booking]
verify_jwt = false

[functions.payment-callback]
verify_jwt = false

[functions.create-map-booking]
verify_jwt = false

[functions.create-quick-booking]
verify_jwt = false

[functions.cancel-all-map-bookings]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.notify-on-booking-change]
verify_jwt = false

[functions.get-offers]
verify_jwt = false

